### ISSUE TITLE
能否提供 DSDT？

### ISSUE THREAD

**Issue by ghost** [corenel/Z270-HD3-macOS#2]
我也是这个主板，不过 CPU 是 i7 7700k，~~用 MaciASL 生成 DSDT 会报错~~确认是版本过低，用 RehabMan 大神的 1.5 可以用了，用 Clover 提取 DSDT 会导致 Kernel Panic，如果你有现成的 DSDT 我就可以省事了。

**Comment by ghost** [comment]
现在的情况是唤醒变重启，可能是因为 AppleLPC 没有加载，USB 也没有识别出所有接口。

**Comment by corenel** [comment]
抱歉, 我没有用到DSDT的patch, 所以也没提取.
你如果硬件合适的话(比如说是按照tonymacx86上的推荐兼容配置), 直接用MultiBeast装对应的kext就好了.
KabyLake的CPU我没有用过, 记得应该就是`config.plist`的IntelGFX那里要设成`0x59128086`之类的吧? 你可以参照[这里](https://hackintosher.com/guides/high-sierra-install-full-guide/)的教程.
USB接口的问题应该是`config.plist`加几个patch, 然后配上对应的kext就行了, 并不需要手动打DSDT的补丁.
唤醒变重启这个我没有遇到过, 抱歉也不清楚具体原因.
总而言之, 台式机还是比笔记本好折腾多了.

**Comment by ghost** [comment]
@corenel 哈哈，我也是笔记本装不上就换成台式机了，不过好像 MaciASL 补丁源里面的 patch 都比较旧了，都是几年前的（比如 7～9 系），没有 100 以上的芯片组的 patch。

**Comment by corenel** [comment]
@iVanilla 所以推荐直接用[MultiBeast](https://www.tonymacx86.com/resources/multibeast-high-sierra-10-2-0.360/)好了

**Comment by ghost** [comment]
@corenel  ![Screen Shot 1397-01-29 at 12.18.33 PM.png](https://i.loli.net/2018/04/18/5ad6c7a89f37a.png)

USB 是这样的，没有显示 2.0 的 Bus。

**Comment by corenel** [comment]
我看了一下也没有显示USB2.0的bus, 不过把键盘之类的插在主板后面的USB2.0口上确实能用.
可能是macOS把USB2.0也认为是USB3.0的口了?
<img width="863" alt="screen shot 2018-04-18 at 12 33 01 pm" src="https://user-images.githubusercontent.com/8099273/38911902-ee16c5cc-4304-11e8-91eb-3346c6e4d207.png">

**Comment by ghost** [comment]
@corenel 如果这样的话那 USB 应该没问题了

**Comment by ghost** [comment]
@corenel 对了，你能正常加载原生电源管理吗？我这里不能加载 AppleLPC.kext，自然也无法加载 AICPM
